{
    "success": true,
    "servers": [
        {
            "id": 140,
            "name": "W-UP DE",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:31280/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d233b7a6ad8.jpeg",
            "wormworld": 0,
            "timmap": 8,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 139,
            "name": "𓌹 ڪابــو 𖡬‎",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32196/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d232e075cbf.png",
            "timmap": 17,
            "wormworld": 0,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 138,
            "name": "Glitch show1",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d23280e7cf2.jpg",
            "timmap": 1,
            "wormworld": 1,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 137,
            "name": "W-UP DE",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:31050/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 21,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 136,
            "name": "Glitch Berlin",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:30201/wormy",
            "image": "https://wormup.in/api/servers/images/67fc7f1362356.jpg",
            "imageUrl": "https://www.tiktok.com/@berlin52.hz",
            "wormworld": 0,
            "timmap": 19,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 135,
            "name": "Saeedi Gaming",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32625/wormy",
            "image": "https://wormup.in/api/servers/images/67fc7e649d1e5.jpg",
            "imageUrl": "https://www.facebook.com/SaeediGaming86",
            "wormworld": 0,
            "timmap": 18,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 134,
            "name": "Sherwani ",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67fc7dd9c0ff6.jpg",
            "timmap": 7,
            "wormworld": 6,
            "imageUrl": "https://www.facebook.com/people/Sherwani/100083316140496",
            "mydata": 1
        },
        {
            "id": 133,
            "name": "tik 𓌹 𝙆𝘼𝙄𝙈 ✗",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32708/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67fc7eba87a65.png",
            "timmap": 5,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@karim_g11",
            "mydata": 1
        },
        {
            "id": 132,
            "name": "tik shadi",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32017/wormy",
            "image": "https://wormup.in/api/servers/images/67fc7e3f1ef94.png",
            "imageUrl": "https://www.tiktok.com/@xxshadi1",
            "wormworld": 0,
            "timmap": 9,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 131,
            "name": "𝐀𝐎𝐓𝐎 | أوتو",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2339956a63.jpeg",
            "timmap": 4,
            "wormworld": 5,
            "imageUrl": "https://www.tiktok.com/@aoto_gaming",
            "mydata": 1
        },
        {
            "id": 130,
            "name": "𝐑𝐀𝐘𝐀𝐍",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d233d8bb946.jpeg",
            "wormworld": 3,
            "timmap": 3,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 129,
            "name": "ELSHRK🅰️WY⚡️UP",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d23253a75d2.jpeg",
            "timmap": 10,
            "wormworld": 9,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 128,
            "name": "𝐒𝐀i𝐅",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:31050/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d233f17ec77.jpeg",
            "wormworld": 0,
            "timmap": 11,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 127,
            "name": "3𝐀𝐉𝐆𝐀 𝐆𝐀𝐌𝐍𝐆",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32567/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d231a045cc9.jpeg",
            "wormworld": 0,
            "timmap": 13,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 126,
            "name": "𝐇α𝓇𝓐ᵐ.❶Ѳ❸",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:30956/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2351885f54.png",
            "wormworld": 0,
            "timmap": 12,
            "imageUrl": "https://www.tiktok.com/@haram.103",
            "mydata": 1
        },
        {
            "id": 125,
            "name": "𝒜bdessalam ️",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2335723034.jpeg",
            "timmap": 2,
            "wormworld": 4,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 124,
            "name": "𝑶𝐌🅰𝐑",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:31886/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d232b65f259.jpg",
            "timmap": 14,
            "wormworld": 0,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 123,
            "name": "╰ ᘓɹ̇ᒪᓄב 👑╮",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d1ba36978ae.png",
            "timmap": 6,
            "wormworld": 7,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 122,
            "name": "Glitch show",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:31403/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2317f1fb15.jpeg",
            "wormworld": 2,
            "timmap": 15,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 121,
            "name": "Moath UP",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:30501/wormy",
            "status": 1,
            "wormworld": 0,
            "image": "https://wormup.in/api/servers/images/67d22e0d6c4b9.jpeg",
            "timmap": 16,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 120,
            "name": "W-UP DE1",
            "region": "de",
            "serverUrl": "wss://fra-c.wormate.io:30988/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 20,
            "status": 1,
            "mydata": 0
        },
        {
            "id": 119,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 118,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 117,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 116,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 115,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 114,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 113,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 112,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 111,
            "name": "W-UP BR",
            "region": "br",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 9,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 110,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:31886/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 14,
            "status": 1,
            "mydata": 0
        },
        {
            "id": 109,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32567/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 13,
            "status": 1,
            "mydata": 0
        },
        {
            "id": 108,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:30956/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 12,
            "status": 1,
            "mydata": 0
        },
        {
            "id": 107,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:31845/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2f1040d943.png",
            "timmap": 11,
            "wormworld": 0,
            "imageUrl": "",
            "mydata": 0
        },
        {
            "id": 106,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2f0c6a6386.png",
            "wormworld": 9,
            "timmap": 10,
            "imageUrl": "",
            "mydata": 0
        },
        {
            "id": 105,
            "name": "W-UP FR",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32044/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2f11714040.png",
            "wormworld": 0,
            "timmap": 9,
            "imageUrl": "",
            "mydata": 0
        },
        {
            "id": 104,
            "name": "𝐝𝐞𝐧𝐮𝐮𝐬𝐡",
            "region": "fr",
            "serverUrl": "wss://gra-a.wormate.io:31038/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2366cc12ac.jpeg",
            "wormworld": 0,
            "timmap": 0,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 103,
            "name": "𝐑𝐀𝐘𝐀𝐍",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2cebe10435.jpeg",
            "timmap": 6,
            "wormworld": 7,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 102,
            "name": "7ＯＤＡ  ＧＡＭＩＮＧ",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d236c28948b.png",
            "timmap": 5,
            "wormworld": 3,
            "imageUrl": "https://www.tiktok.com/@m3top1",
            "mydata": 1
        },
        {
            "id": 101,
            "name": "هستور سنايب",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d236e4c2064.jpeg",
            "timmap": 7,
            "wormworld": 6,
            "imageUrl": "https://www.tiktok.com/@hstor.snipe",
            "mydata": 1
        },
        {
            "id": 100,
            "name": "亗Eᒪ-TᗩᗯIᒪ㋰",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2f0275f546.jpeg",
            "timmap": 4,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@el_tawil8",
            "mydata": 1
        },
        {
            "id": 99,
            "name": "《 3𝙇𝙇𝘼𝙒𝙄 》",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32017/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2372248f38.jpeg",
            "timmap": 8,
            "wormworld": 0,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 98,
            "name": "★彡جهنم彡★",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d236aad2fcb.png",
            "timmap": 3,
            "wormworld": 5,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 97,
            "name": "𝐌𝐀𝐍𝑶",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2efa00a117.png",
            "timmap": 2,
            "wormworld": 4,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 96,
            "name": "515 🇵🇸",
            "region": "fr",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2f0054f096.jpeg",
            "timmap": 1,
            "wormworld": 1,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 95,
            "name": "❄️ SCD Muội Muội",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae5b5e7840.jpg",
            "timmap": 2,
            "wormworld": 4,
            "imageUrl": "https://www.facebook.com/profile.php?id=100092254689927",
            "mydata": 0
        },
        {
            "id": 94,
            "name": "GLITCH 🙈 NOURA",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/689d4ac041d1b.jpg",
            "timmap": 3,
            "wormworld": 3,
            "imageUrl": "https://www.tiktok.com/@glitchnoura",
            "mydata": 0
        },
        {
            "id": 93,
            "name": "🍒Cherry Land",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae623e3fe5.png",
            "timmap": 4,
            "wormworld": 6,
            "imageUrl": "https://www.facebook.com/Cherry9123",
            "mydata": 0
        },
        {
            "id": 92,
            "name": "💎🪓🅺🅷𝐿𝑒𝒶𝓃𝑔 168",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32708/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae653d16db.jpg",
            "timmap": 5,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/KHLeangGaming168",
            "mydata": 0
        },
        {
            "id": 91,
            "name": "VQH.Gaming",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae68c9883f.jpg",
            "timmap": 6,
            "wormworld": 8,
            "imageUrl": "https://www.tiktok.com/@vqh.48",
            "mydata": 0
        },
        {
            "id": 90,
            "name": "ᵀᶜᵀⱽ Tuấn Cảnh TV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae6d4e1a59.jpg",
            "timmap": 7,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/tuancanhTCTV",
            "mydata": 0
        },
        {
            "id": 89,
            "name": "🔥🐉 61c.39239",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31280/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae6ff03f29.jpg",
            "timmap": 8,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/profile.php?id=100076038386454",
            "mydata": 0
        },
        {
            "id": 88,
            "name": "ᴬᴱ🆃🆅🆃🎤Cậu còi TV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32017/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae73246582.jpg",
            "timmap": 9,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/profile.php?id=100064318623308",
            "mydata": 0
        },
        {
            "id": 87,
            "name": "❄️SCD.𝑯𝒂̣̂𝒖 𝑲𝒖𝒏𝒛",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae75de207e.jpg",
            "timmap": 10,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@haukunz76",
            "mydata": 0
        },
        {
            "id": 86,
            "name": "Xà Tinh Gaming",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:30956/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae7f3f3b51.jpg",
            "timmap": 12,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/thuan151084",
            "mydata": 0
        },
        {
            "id": 85,
            "name": "💰🆅🅶💸 VIỆT KIÊN🌹",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32567/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae82903ee4.jpg",
            "timmap": 13,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/profile.php?id=100063915230765",
            "mydata": 0
        },
        {
            "id": 84,
            "name": "🎁KHUN ACE🎁",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31886/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae85c954c0.jpg",
            "timmap": 14,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/khunace168",
            "mydata": 0
        },
        {
            "id": 83,
            "name": "🌈🆂🅷❤️ Sam Vịt",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31403/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae89c1495c.jpg",
            "timmap": 15,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/Samtutinhhoa",
            "mydata": 0
        },
        {
            "id": 82,
            "name": "🍓Cu Trường Gaming🌸",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:30501/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae8cfb7742.jpg",
            "timmap": 16,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@wormate.iolive",
            "mydata": 0
        },
        {
            "id": 81,
            "name": "🔥🐉 Ngà ăn tỏi GM",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32196/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae8f596605.jpg",
            "timmap": 17,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/Ngangao000",
            "mydata": 0
        },
        {
            "id": 80,
            "name": "💣Trường Bom TV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32625/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae934eafbf.jpg",
            "timmap": 18,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/truongbomgaming",
            "mydata": 0
        },
        {
            "id": 79,
            "name": "ᴭ🦜ℂ𝕙𝕚𝕞𝕊ơ𝕟ℂ𝕒🏹",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:30201/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae9682693b.jpg",
            "timmap": 19,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/profile.php?id=100086944465949",
            "mydata": 0
        },
        {
            "id": 78,
            "name": "🍑 Chung Ruồi Gaming",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:30988/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682ae9895b909.jpg",
            "timmap": 20,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/Cr.chungruoigaming",
            "mydata": 0
        },
        {
            "id": 77,
            "name": "FB: Girl ADH",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32249/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c92efa4790.jpg",
            "timmap": 21,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/profile.php?id=100075939892854",
            "mydata": 0
        },
        {
            "id": 76,
            "name": "🥕 Akira Gaming",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9320cf160.jpg",
            "timmap": 22,
            "wormworld": 1,
            "imageUrl": "https://www.facebook.com/profile.php?id=100077450623669",
            "mydata": 0
        },
        {
            "id": 75,
            "name": "Tiểu Thư Ký Gaming",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c934c699d9.jpg",
            "timmap": 23,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/tieuthukygaming",
            "mydata": 0
        },
        {
            "id": 74,
            "name": "FB🐰HoàngHônTV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c93799d678.jpg",
            "timmap": 24,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/hoanghontv",
            "mydata": 0
        },
        {
            "id": 73,
            "name": "⛄SQ🌺Salju Qaseh🐰",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32708/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c93a2917ab.jpg",
            "timmap": 25,
            "wormworld": 0,
            "imageUrl": "https://www.facebook.com/SQSaljuQaseh",
            "mydata": 0
        },
        {
            "id": 72,
            "name": "🍄🅼🅲Mạnh Còi TV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c93c8cdf47.jpg",
            "timmap": 26,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@hoaxuanmanh93",
            "mydata": 0
        },
        {
            "id": 71,
            "name": "CẬUBIN 🐘❤️❤️❤️",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c94025a2e0.jpg",
            "timmap": 27,
            "wormworld": 5,
            "imageUrl": "https://www.tiktok.com/@caubinranio",
            "mydata": 0
        },
        {
            "id": 70,
            "name": "Lộc Sẹo TV",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31280/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9436c648e.jpg",
            "timmap": 28,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@locseotv",
            "mydata": 0
        },
        {
            "id": 69,
            "name": "Cô Chủ Nhỏ🖤",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32017/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9458e47ef.jpg",
            "timmap": 29,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@uyen_baby1",
            "mydata": 0
        },
        {
            "id": 68,
            "name": "CG 💚 Liên Tủn 💚",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c947249369.jpg",
            "timmap": 30,
            "wormworld": 9,
            "imageUrl": "https://www.facebook.com/cglientun",
            "mydata": 0
        },
        {
            "id": 67,
            "name": "🌸ᵀᴵᴷᵀᴼᴷ S𝐄N Đ𝐀́ ᴳᴹ",
            "region": "sg",
            "serverUrl": "wss://sin-b.wormate.io:31050/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c94d828fc6.jpg",
            "timmap": 31,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@senda_gaming",
            "mydata": 0
        },
        {
            "id": 66,
            "name": "🦋⁶⁸⁶⁸ Cu Lếch TV",
            "region": "sg",
            "serverUrl": "wss://sin-b.wormate.io:30956/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9500e2fa8.jpg",
            "timmap": 32,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@culech247",
            "mydata": 0
        },
        {
            "id": 65,
            "name": "Hà Hà Xuka",
            "region": "sg",
            "serverUrl": "wss://sin-b.wormate.io:32567/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9527280d8.png",
            "timmap": 33,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@hxuka94",
            "mydata": 0
        },
        {
            "id": 64,
            "name": "🐳𝐋𝐨𝐧𝐠 𝐇ả𝐢🌊",
            "region": "sg",
            "serverUrl": "wss://sin-b.wormate.io:31886/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c9545cf622.jpg",
            "timmap": 34,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@longhai1188",
            "mydata": 0
        },
        {
            "id": 63,
            "name": "🔥Đô𝐋𝐚❣️",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31403/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c95641c5da.jpg",
            "timmap": 35,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@dola.gamer",
            "mydata": 0
        },
        {
            "id": 62,
            "name": "🐳𝐒𝐚𝐧𝐠 𝐒𝐮𝐧🌊",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:30501/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/682c958d91644.jpg",
            "timmap": 36,
            "wormworld": 0,
            "imageUrl": "https://www.tiktok.com/@sangsunn98",
            "mydata": 0
        },
        {
            "id": 61,
            "name": "Endha Agustin",
            "region": "sg",
            "serverUrl": "wss://sin-b.wormate.io:32196/wormy",
            "image": "https://wormup.in/api/servers/images/682c95b19a117.jpg",
            "wormworld": 0,
            "status": 1,
            "timmap": 37,
            "imageUrl": "https://www.facebook.com/Endha.Agustin",
            "mydata": 0
        },
        {
            "id": 60,
            "name": "❄️ SCD 𝕮𝖎𝖓𝖉𝖞𝖓𝖆𝖓𝖆",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/682c95d42aefd.jpg",
            "wormworld": 2,
            "status": 1,
            "timmap": 1,
            "imageUrl": "https://www.tiktok.com/@tong.cindy",
            "mydata": 0
        },
        {
            "id": 59,
            "name": "🐻 ADH Diêm Vương",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31050/wormy",
            "image": "https://wormup.in/api/servers/images/682ae7b1a214a.jpg",
            "imageUrl": "https://www.facebook.com/vuongvanle1986",
            "wormworld": 0,
            "timmap": 11,
            "status": 1,
            "mydata": 0
        },
        {
            "id": 58,
            "name": "سنغافورا",
            "region": "sg",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "mydata": 0,
            "status": 1
        },
        {
            "id": 57,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 56,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 55,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 54,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 53,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 52,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 51,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 50,
            "name": "WW",
            "region": "jp",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 49,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 48,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 47,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 46,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 45,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 44,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 43,
            "name": "WW",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 42,
            "name": "SRTIRAQTIK",
            "region": "au",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718e55984.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 41,
            "name": "gb",
            "region": "au",
            "serverUrl": "wss://syd-a.wormate.io:31238/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "wormworld": 0,
            "timmap": 0,
            "imageUrl": "",
            "mydata": 0
        },
        {
            "id": 40,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 39,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 38,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 37,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 36,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 35,
            "name": "WW",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 34,
            "name": "ABOARQAN",
            "region": "ca",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718e6101d.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 33,
            "name": "W-UP LT",
            "region": "ca",
            "serverUrl": "wss://dal-b.wormate.io:30786/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 32,
            "name": "ABOARQAN",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718eefd9e.png",
            "imageUrl": "",
            "wormworld": 9,
            "timmap": 9,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 31,
            "name": "HSG❤️",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718ee88b2.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 1,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 30,
            "name": "FF FAMILY FOREVER",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718edae4e.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 7,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 29,
            "name": "DF GAMING",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718ec8d3b.png",
            "imageUrl": "https://www.tiktok.com/@donfrankie?_t=ZT-8u4fAo8WMAg&_r=1",
            "wormworld": 6,
            "timmap": 6,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 28,
            "name": "LEMANZ GAMING",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718ebf6da.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 4,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 27,
            "name": "GYA 09",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718eae648.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 5,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 26,
            "name": "SUPERMOD IMMY",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718e9f289.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 3,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 25,
            "name": "⎳𝕄℣🔱  LA MERA VENA",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a07213c4be1.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 2,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 24,
            "name": "【V】【I】【P】【E】【R】",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a071f3b9f7f.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 8,
            "status": 0,
            "mydata": 1
        },
        {
            "id": 23,
            "name": "ℍᏕ₲⚡🔱⎳𝕄℣",
            "region": "us",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "image": "https://wormup.in/api/servers/images/687c5ebd1fcc1.jpg",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 0,
            "status": 1,
            "mydata": 1
        },
        {
            "id": 22,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 21,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 20,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 19,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 18,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 17,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 16,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 15,
            "name": "WW",
            "region": "gb",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 14,
            "name": "WW",
            "region": "uae",
            "serverUrl": "wss://fra-c.wormate.io:32285/wormy",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 9,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 13,
            "name": "AFG 💀AZIZI 💀YT",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32095/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f619ea.png",
            "imageUrl": "",
            "wormworld": 8,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 12,
            "name": "JOGOS ALI",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32262/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f55095.png",
            "imageUrl": "",
            "wormworld": 7,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 11,
            "name": "SHERAZ",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32026/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f49307.png",
            "imageUrl": "",
            "wormworld": 6,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 10,
            "name": "COLL@YT🥶",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:31965/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f374af.png",
            "imageUrl": "",
            "wormworld": 5,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 9,
            "name": "QASIM GAMING",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32064/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f26c94.png",
            "imageUrl": "",
            "wormworld": 4,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 8,
            "name": "༄●⃝ᶫꪜᴳᴬᴹᴵᴺᴳ×͜ㅤ❼❼",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32103/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f1d7f8.png",
            "imageUrl": "",
            "wormworld": 3,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 7,
            "name": "FIRE@YT",
            "region": "uae",
            "serverUrl": "wss://fra-c.wormate.io:32609/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f15b49.png",
            "imageUrl": "",
            "wormworld": 2,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 6,
            "name": "ALI GAMING",
            "region": "uae",
            "serverUrl": "wss://fra-c.wormate.io:32053/wormy",
            "image": "https://wormup.in/api/servers/images/external_68a0718f08ef7.png",
            "imageUrl": "",
            "wormworld": 1,
            "timmap": 0,
            "status": 0,
            "mydata": 0
        },
        {
            "id": 5,
            "name": "𝐀𝐎𝐎 | أوتوو",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32703/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d24545e0445.jpeg",
            "wormworld": 4,
            "timmap": 0,
            "imageUrl": "https://www.tiktok.com/@aoto_gaming",
            "mydata": 1
        },
        {
            "id": 4,
            "name": "بو يوسف",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32650/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d237f1711ea.jpg",
            "timmap": 0,
            "wormworld": 3,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 3,
            "name": "moath up",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:31353/wormy",
            "status": 1,
            "image": "https://wormup.in/api/servers/images/67d2393b6b81b.jpeg",
            "timmap": 0,
            "wormworld": 2,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 2,
            "name": "╰ ᘓɹ̇ᒪᓄב 👑╮",
            "region": "uae",
            "serverUrl": "wss://dxb-a.wormate.io:32703/wormy",
            "status": 0,
            "image": "https://wormup.in/api/servers/images/67d2496cd04ed.png",
            "wormworld": 1,
            "timmap": 0,
            "imageUrl": "",
            "mydata": 1
        },
        {
            "id": 1,
            "name": "test",
            "region": "uae",
            "serverUrl": "wss://wormup.in:9998",
            "image": "https://wormup.in/api/servers/images/default-server.png",
            "imageUrl": "",
            "wormworld": 0,
            "timmap": 1,
            "mydata": 0,
            "status": 1
        }
    ]
}
